language: csharp
solution: unit-testing-using-dotnet-test.sln
install:
  - nuget restore unit-testing-using-dotnet-test.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release unit-testing-using-dotnet-test.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./PrimeService.Tests.bin/Release/netcoreapp3.1/PrimeService.Tests.dll

  
